spring.application.name=backend
spring.mongodb.uri=mongodb://root:secret_password@localhost:27017/documind_db?authSource=admin
spring.data.mongodb.auto-index-creation=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
# 256-bit secret key (Example base64 string)
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Expiration: 1 day in milliseconds (86,400,000 ms)
app.jwt.expiration=86400000
