spring.application.name=backend
#spring.mongodb.uri=mongodb://root:secret_password@localhost:27017/documind_db?authSource=admin
#spring.data.mongodb.auto-index-creation=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# 256-bit secret key (Example base64 string)
app.jwt.secret=${JWT_SECRET}
# Expiration: 1 day in milliseconds (86,400,000 ms)
app.jwt.expiration=86400000

app.security.admin-key=${ADMIN_KEY}

spring.datasource.url=jdbc:postgresql://postgres:5432/documind

spring.datasource.username=documind

spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.ai.openai.embedding.options.model=text-embedding-3-small

spring.ai.openai.chat.options.model=gpt-4o-mini

spring.data.redis.host=redis

spring.data.redis.port=6379

spring.data.redis.timeout=2000ms

spring.data.redis.lettuce.pool.max-active=16

spring.data.redis.lettuce.pool.max-idle=8

spring.data.redis.lettuce.pool.min-idle=2

management.endpoints.web.exposure.include=health,metrics,prometheus

management.endpoint.prometheus.access=UNRESTRICTED

management.prometheus.metrics.export.enabled=true